//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tbleMobile
{
    public tbleMobile()
    {
        this.tblReferenceSites = new HashSet<tblReferenceSite>();
        this.tblSpecifications = new HashSet<tblSpecification>();
    }

    public int MobileID { get; set; }
    public string MobileName { get; set; }
    public string MobileDescription { get; set; }
    public string MobileImage { get; set; }

    public virtual ICollection<tblReferenceSite> tblReferenceSites { get; set; }
    public virtual ICollection<tblSpecification> tblSpecifications { get; set; }
}

public partial class tblReferenceSite
{
    public int ReferenceSiteID { get; set; }
    public string ReferenceSiteName { get; set; }
    public string ReferenceSiteLink { get; set; }
    public Nullable<int> MobileID { get; set; }

    public virtual tbleMobile tbleMobile { get; set; }
}

public partial class tblSpecification
{
    public int SpecificationID { get; set; }
    public string FrontCamera { get; set; }
    public string BackCamera { get; set; }
    public string Processor { get; set; }
    public string RAM { get; set; }
    public string Storage { get; set; }
    public string OS { get; set; }
    public string BatteryCapacity { get; set; }
    public Nullable<int> MobileID { get; set; }

    public virtual tbleMobile tbleMobile { get; set; }
}

public partial class tblUser
{
    public int UsersID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string EmailAddress { get; set; }
    public string Password { get; set; }
    public string MobileNo { get; set; }
    public Nullable<bool> Status { get; set; }
    public int UserTypeID { get; set; }

    public virtual tblUserType tblUserType { get; set; }
}

public partial class tblUserType
{
    public tblUserType()
    {
        this.tblUsers = new HashSet<tblUser>();
    }

    public int UserTypeID { get; set; }
    public string UserTypeName { get; set; }

    public virtual ICollection<tblUser> tblUsers { get; set; }
}

public partial class DoLogin_Result
{
    public int UsersID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string EmailAddress { get; set; }
    public string Password { get; set; }
    public string MobileNo { get; set; }
    public Nullable<bool> Status { get; set; }
    public int UserTypeID { get; set; }
}

public partial class GetAllMobiles_Result
{
    public int MobileID { get; set; }
    public string MobileName { get; set; }
    public string MobileDescription { get; set; }
    public string MobileImage { get; set; }
}

public partial class GetAllUsers_Result
{
    public int UsersID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string EmailAddress { get; set; }
    public string Password { get; set; }
    public string MobileNo { get; set; }
    public Nullable<bool> Status { get; set; }
    public int UserTypeID { get; set; }
}

public partial class GetAUser_Result
{
    public int UsersID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string EmailAddress { get; set; }
    public string Password { get; set; }
    public string MobileNo { get; set; }
    public Nullable<bool> Status { get; set; }
    public int UserTypeID { get; set; }
}

public partial class GetUserType_Result
{
    public int UserTypeID { get; set; }
    public string UserTypeName { get; set; }
}
