//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class TourNinjasDatabaseEntities : DbContext
{
    public TourNinjasDatabaseEntities()
        : base("name=TourNinjasDatabaseEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tableUser> tableUsers { get; set; }
    public virtual DbSet<tableUsersType> tableUsersTypes { get; set; }
    public virtual DbSet<tableCity> tableCities { get; set; }
    public virtual DbSet<tableCountry> tableCountries { get; set; }
    public virtual DbSet<tableRestaurant> tableRestaurants { get; set; }

    public virtual int DeleteUser(Nullable<int> userid)
    {
        var useridParameter = userid.HasValue ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUser", useridParameter);
    }

    public virtual ObjectResult<getUsers_Result> getUsers()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUsers_Result>("getUsers");
    }

    public virtual ObjectResult<GetAllUserTypes_Result> GetAllUserTypes()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllUserTypes_Result>("GetAllUserTypes");
    }

    public virtual int deleteUserType(Nullable<int> usertypeID)
    {
        var usertypeIDParameter = usertypeID.HasValue ?
            new ObjectParameter("usertypeID", usertypeID) :
            new ObjectParameter("usertypeID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteUserType", usertypeIDParameter);
    }

    public virtual ObjectResult<getCities_Result> getCities()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCities_Result>("getCities");
    }

    public virtual ObjectResult<getCountry_Result> getCountry()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCountry_Result>("getCountry");
    }

    public virtual ObjectResult<getRestaurants_Result> getRestaurants()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRestaurants_Result>("getRestaurants");
    }

    public virtual int deleteRestaurants(Nullable<int> rid)
    {
        var ridParameter = rid.HasValue ?
            new ObjectParameter("rid", rid) :
            new ObjectParameter("rid", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteRestaurants", ridParameter);
    }

    public virtual ObjectResult<getCityRestaurants_Result> getCityRestaurants(Nullable<int> cid)
    {
        var cidParameter = cid.HasValue ?
            new ObjectParameter("cid", cid) :
            new ObjectParameter("cid", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCityRestaurants_Result>("getCityRestaurants", cidParameter);
    }
}
