//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tableCity
{
    public tableCity()
    {
        this.tableRestaurants = new HashSet<tableRestaurant>();
    }

    public int cityID { get; set; }
    public string cityName { get; set; }
    public string cityDescription { get; set; }
    public Nullable<int> cityCountry { get; set; }

    public virtual tableCountry tableCountry { get; set; }
    public virtual ICollection<tableRestaurant> tableRestaurants { get; set; }
}

public partial class tableCountry
{
    public tableCountry()
    {
        this.tableCities = new HashSet<tableCity>();
    }

    public int cityCountry { get; set; }
    public string cityCountryName { get; set; }

    public virtual ICollection<tableCity> tableCities { get; set; }
}

public partial class tableRestaurant
{
    public int restaurantID { get; set; }
    public string restaurantName { get; set; }
    public string restaurantDescription { get; set; }
    public string restaurantImage { get; set; }
    public Nullable<int> cityID { get; set; }

    public virtual tableCity tableCity { get; set; }
}

public partial class tableUser
{
    public int userID { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public string email { get; set; }
    public string phoneNumber { get; set; }
    public string password { get; set; }
    public int userTypeID { get; set; }

    public virtual tableUsersType tableUsersType { get; set; }
}

public partial class tableUsersType
{
    public tableUsersType()
    {
        this.tableUsers = new HashSet<tableUser>();
    }

    public int userTypeID { get; set; }
    public string userTypeName { get; set; }

    public virtual ICollection<tableUser> tableUsers { get; set; }
}

public partial class GetAllUserTypes_Result
{
    public int userTypeID { get; set; }
    public string userTypeName { get; set; }
}

public partial class getCities_Result
{
    public int cityID { get; set; }
    public string cityName { get; set; }
    public string cityDescription { get; set; }
    public Nullable<int> cityCountry { get; set; }
}

public partial class getCityRestaurants_Result
{
    public int restaurantID { get; set; }
    public string restaurantName { get; set; }
    public string restaurantDescription { get; set; }
    public string restaurantImage { get; set; }
    public Nullable<int> cityID { get; set; }
}

public partial class getCountry_Result
{
    public int cityCountry { get; set; }
    public string cityCountryName { get; set; }
}

public partial class getRestaurants_Result
{
    public int restaurantID { get; set; }
    public string restaurantName { get; set; }
    public string restaurantDescription { get; set; }
    public string restaurantImage { get; set; }
    public Nullable<int> cityID { get; set; }
}

public partial class getUsers_Result
{
    public int userID { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public string email { get; set; }
    public string phoneNumber { get; set; }
    public string password { get; set; }
    public int userTypeID { get; set; }
}
