USE [master]
GO

/****** Object:  Database [BestMobilePh53]    Script Date: 22/04/2020 18:38:34 ******/
CREATE DATABASE [BestMobilePh53]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BestMobilePh53', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\BestMobilePh53.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BestMobilePh53_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\BestMobilePh53_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BestMobilePh53] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BestMobilePh53].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BestMobilePh53] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BestMobilePh53] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BestMobilePh53] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BestMobilePh53] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BestMobilePh53] SET ARITHABORT OFF 
GO

ALTER DATABASE [BestMobilePh53] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BestMobilePh53] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BestMobilePh53] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BestMobilePh53] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BestMobilePh53] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BestMobilePh53] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BestMobilePh53] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BestMobilePh53] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BestMobilePh53] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BestMobilePh53] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BestMobilePh53] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BestMobilePh53] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BestMobilePh53] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BestMobilePh53] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BestMobilePh53] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BestMobilePh53] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BestMobilePh53] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BestMobilePh53] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BestMobilePh53] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BestMobilePh53] SET  MULTI_USER 
GO

ALTER DATABASE [BestMobilePh53] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BestMobilePh53] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BestMobilePh53] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BestMobilePh53] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BestMobilePh53] SET  READ_WRITE 
GO

